Tubs18 team1
BassMonster/FeatureIDE pull request #3
Opened 2018-09-27 13:42 UTC by Indycate

finished issues #603 and #809

2018-09-28 08:08 UTC, BassMonster commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/properties/language/ILanguage.java
> +	 * @return
remove comment or explain method

2018-09-28 08:10 UTC, BassMonster commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/properties/language/German.java
> +
remove the empty line

2018-09-28 08:11 UTC, BassMonster commented
looks fine @PaulWestphal

2018-10-07 13:22 UTC, PaulWestphal requested changes

2018-10-07 13:22 UTC, PaulWestphal commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/FeatureModelEditor.java
> +	public boolean hasLayoutInformation() {
This method should check whether layout information is available, the way you do it in setInput. Manually setting a boolean like this can lead to bugs. You shouldn't need the "existLayoutInformation" boolean at all.

2018-10-09 09:08 UTC, ThisIsATunaSandwich commented
@PaulWestphal 

Names changed

2018-10-09 10:05 UTC, PaulWestphal commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/FeatureModelEditor.java
> +	public void createLayoutInformation() {
This method will never be called from another class and shouldn't be public.

2018-10-09 10:41 UTC, ThisIsATunaSandwich commented
@PaulWestphal 

createLayoutInformation() changed to private

2018-10-09 11:52 UTC, merged